export const GET_SELLER="seller/get"
export const GET_BUYER="buyer/get"
export const GET_SELLER_SUCCESS="seller/success"
export const GET_BUYER_SUCCESS="buyer/succcess"
export const GET_SELLER_ERROR="seller/error"
export const GET_BUYER_ERROR="buyer/error"